apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    uid: PBFA97CFB590B2093
    isDefault: false
    jsonData:
      httpMethod: GET
      timeInterval: "5s"