auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9097

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093

# Important: Allow out-of-order logs
limits_config:
  # Allow out-of-order logs up to 2 hours old
  unordered_writes: true
  max_query_series: 100000
  max_query_parallelism: 2
  
ingester:
  # Allow chunks to be updated for 2 hours
  chunk_idle_period: 2h
  max_chunk_age: 2h
  chunk_retain_period: 5m
  # Accept out-of-order logs
  wal:
    enabled: true
    dir: /loki/wal

analytics:
  reporting_enabled: false